name: summernote_editor
description: Summernote-powered rich HTML editor for Flutter on Android, iOS, and web.
version: 1.0.0
repository: https://github.com/aungzwin10/summernote-editor
issue_tracker: https://github.com/aungzwin10/summernote-editor/issues

topics:
  - html-editor
  - rich-text-editor
  - summernote
  - wysiwyg

platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=3.13.5 <4.0.0'
  flutter: ">=3.47.6"

dependencies:
  flutter:
    sdk: flutter
  # webview plugin
  flutter_inappwebview: ^6.1.5
  # plugin to get webview's visible fraction for keyboard height adjustment
  visibility_detector: ^0.4.0+2
  # plugin to get when the keyboard is hidden via back (Android)
  # or "done" (iOS) to reset the editor's height
  flutter_keyboard_visibility: ^7.0.1
  # plugin for @internal annotation
  meta: ^1.19.0
  # modern browser APIs and Wasm-compatible JavaScript interop
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # plugin to help maintain effective Dart standards
  lints: ^6.1.0


flutter:

  assets:
    - packages/summernote_editor/assets/summernote.html
    - packages/summernote_editor/assets/summernote-no-plugins.html
    - packages/summernote_editor/assets/summernote-lite.min.css
    - packages/summernote_editor/assets/summernote-lite-dark.css
    - packages/summernote_editor/assets/summernote-lite.min.js
    - packages/summernote_editor/assets/jquery.min.js
    - packages/summernote_editor/assets/font/summernote.eot
    - packages/summernote_editor/assets/font/summernote.ttf
    - packages/summernote_editor/assets/font/summernote.woff
    - packages/summernote_editor/assets/font/summernote.woff2
    - packages/summernote_editor/assets/plugins/summernote-at-mention/summernote-at-mention.js
